# Generated by Django 4.1.2 on 2022-10-21 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_F', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_P', models.IntegerField()),
                ('precio_P', models.IntegerField()),
                ('imagen_P', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Pr', models.CharField(max_length=45)),
                ('apellido_Pr', models.CharField(max_length=45)),
                ('direccion_Pr', models.CharField(max_length=45)),
                ('telefono_Pr', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_T', models.CharField(max_length=45)),
                ('apellido_T', models.CharField(max_length=45)),
                ('direccion_T', models.CharField(max_length=45)),
                ('telefono_T', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_P', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barApp.producto')),
                ('id_Pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barApp.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_F', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barApp.factura')),
                ('cod_P', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barApp.producto')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='id_T',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barApp.trabajador'),
        ),
    ]
