# Generated by Django 4.1.2 on 2022-10-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barApp', '0002_alter_factura_fecha_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='apellido_Pr',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_P',
            field=models.CharField(default='none', max_length=200, verbose_name='Descripción del producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_P',
            field=models.CharField(default='none', max_length=45, verbose_name='Nombre del '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='correo_Pr',
            field=models.CharField(default='none', max_length=45, verbose_name='Correo del proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_F',
            field=models.DateField(verbose_name='Fecha factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id_T',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barApp.trabajador', verbose_name='Trabajadores'),
        ),
        migrations.AlterField(
            model_name='factura_producto',
            name='cod_F',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barApp.factura', verbose_name='Código Factura'),
        ),
        migrations.AlterField(
            model_name='factura_producto',
            name='cod_P',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barApp.producto', verbose_name='Código Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_P',
            field=models.IntegerField(verbose_name='Cantidad del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_P',
            field=models.ImageField(upload_to=None, verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_P',
            field=models.IntegerField(verbose_name='Precio del producto'),
        ),
        migrations.AlterField(
            model_name='producto_proveedor',
            name='cod_P',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barApp.producto', verbose_name='Código Producto'),
        ),
        migrations.AlterField(
            model_name='producto_proveedor',
            name='id_Pr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barApp.proveedor', verbose_name='Código Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion_Pr',
            field=models.CharField(max_length=45, verbose_name='Dirección del proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nom_Pr',
            field=models.CharField(max_length=45, verbose_name='Nombre del proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_Pr',
            field=models.CharField(max_length=45, verbose_name='Teléfono del proveedor'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='apellido_T',
            field=models.CharField(max_length=45, verbose_name='Apellido del trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='direccion_T',
            field=models.CharField(max_length=45, verbose_name='Dirección del trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nom_T',
            field=models.CharField(max_length=45, verbose_name='Nombre del trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono_T',
            field=models.CharField(max_length=45, verbose_name='Teléfono del trabajador'),
        ),
    ]
