# Generated by Django 4.1.2 on 2022-10-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barApp', '0003_remove_proveedor_apellido_pr_producto_descripcion_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo_Pr',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
