# Generated by Django 4.1.2 on 2022-10-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barApp', '0004_alter_proveedor_correo_pr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='producto_proveedor',
            options={'verbose_name_plural': 'Producto_Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_P',
            field=models.CharField(max_length=45, verbose_name='Nombre del producto'),
        ),
    ]
