# Generated by Django 4.1.2 on 2022-10-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barApp', '0005_alter_factura_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_P',
            field=models.CharField(default='Bebidas', max_length=45, verbose_name='Categoria del producto'),
            preserve_default=False,
        ),
    ]
