# Generated by Django 4.1.2 on 2022-10-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barApp', '0006_producto_categoria_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_P',
            field=models.ImageField(upload_to='static/imagenes/DB', verbose_name='Imagen del producto'),
        ),
    ]
