# Generated by Django 4.1.2 on 2022-11-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barApp', '0008_alter_producto_categoria_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
