# Generated by Django 4.1.2 on 2022-11-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barApp', '0009_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='email',
            field=models.CharField(default='a@a.com', max_length=45, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='apellido_T',
            field=models.CharField(max_length=45, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='direccion_T',
            field=models.CharField(max_length=45, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nom_T',
            field=models.CharField(max_length=45, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono_T',
            field=models.CharField(max_length=45, verbose_name='Teléfono'),
        ),
    ]
